[project]
name = "venv-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-auth>=2.43.0",
    "gspread>=6.2.1",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
]

[tool.uv.workspace]
members = [
    "env-uv",
]
